### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by cryptoquick** [dpc/rostra#15]
It would be nice if there was a basic dark mode that detected the user theme.

I personally prefer high contrast flat black #000000 themes, but it's up to you.

**Comment by dpc** [comment]
Right.

I this there's a way to get dark mode preference from the browser itself, and then just adding bunch of extra rules to css to change some colors...

**Comment by dpc** [comment]
```css
@media (prefers-color-scheme: dark) {
  body {
    background: #000;
    color: #fff;
  }
}

@media (prefers-color-scheme: light) {
  body {
    background: #fff;
    color: #000;
  }
}
```

How would I do web UI without AI... :D
